FROM node:18-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install


# Accept the URL as an argument
ARG VITE_API_BASE_URL
# Set it as an environment variable for the build step
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
# -----------------------

COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]